name: Publish static redirects site
on: { push: { branches: [main] } }
jobs:
  www:
    name: Publish static redirects site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip
      - run: pip install -r requirements.txt
      - run: ./redirects.py
      - run: touch out/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: out

